### ISSUE TITLE
n_sample_cells & n_sample_peaks

### ISSUE THREAD

**Issue by shunyasanuma** [theislab/mubind#137]
Hello, 

How do you decide on `n_sample_cells` & `n_sample_peaks` in the Mouse pancreatic endocrinogenesis (scATAC-seq) Tutorial?
Do you have any benchmarks?

**Comment by ilibarra** [comment]
Making a general decision is difficult because of dataset complexity. Some thoughts below that apply to `pwms+graph` modeling in single-cell. Happy to expand for your potential use case.

- We tested `n_sample_cells` increasingly in four single-cell datasets against scBasset. The current preprint shows results for a fixed number of cells and peaks (5,000, 15,000). Additional values as TSV will be uploaded by mid-Sep at https://github.com/theislab/mubind-benchmark
- Regarding `n_sample_peaks`, from best practices we refer to this comment on feature filtering. https://www.sc-best-practices.org/chromatin_accessibility/quality_control.html#filtering-features 
 In the preprint, we tested feature selection using random or episcanpy. I would recommend random feature selection, and for exploration at least a multiple of the number of cells e.g. 2x-3x.
- Selection for both terms can be more complex if you have an unbalanced cell type in your dataset, and wish to sample cells or peaks for those. The tutorial for pancreas lets you sample cells based on a specific cell_type covariate, and can be adapted for features.
- In pwms+graph full dataset modeling can take a long time. As a general recommendation, anything with at least >1,000-5,000 cells and a random selection of features (>3,000-15,000) is reasonable to setup the initial workflow. Then, in terms of scalability, I would assess the running time based on Graph Layer (off/on), the amount of GPU/memory available, and the total running time based on the strategy to optimize binding layer filters. Let us know if you face computing bottlenecks as new issues.

Thank you!
